### ISSUE TITLE
centos 7 node 7.1 版本安装错误

### ISSUE THREAD

**Issue by lilijialiang** [hotoo/pinyin#114]
具体错误如下

```shell
[root@centos node]# npm install pinyin
npm WARN gentlyRm not removing /root/node/node_modules/.bin/pinyin as it wasn't installed by /root/node/node_modules/pinyin

> nodejieba@2.2.4 install /root/node/node_modules/nodejieba
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/root/node/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
在包含自 ../lib/utils.h：6 的文件中，
                 从 ../lib/nodejieba.h：4，
                 从 ../lib/index.cpp：1:
../../nan/nan.h:43:3: 错误：#error This version of node/NAN/v8 requires a C++11 compiler
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /root/.node-gyp/7.2.0/include/node/v8.h:21,
                 from /root/.node-gyp/7.2.0/include/node/node.h:42,
                 from ../lib/utils.h:4,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: 错误：在指定 -fno-rtti 的情况下不能使用 typeid
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: 错误：在指定 -fno-rtti 的情况下不能使用 typeid
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: 错误：在指定 -fno-rtti 的情况下不能使用 typeid
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: 错误：在指定 -fno-rtti 的情况下不能使用 typeid
In file included from /root/.node-gyp/7.2.0/include/node/node.h:42,
                 from ../lib/utils.h:4,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
/root/.node-gyp/7.2.0/include/node/v8.h: At global scope:
/root/.node-gyp/7.2.0/include/node/v8.h:346: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/7.2.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/7.2.0/include/node/v8.h:363: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/7.2.0/include/node/v8.h:370: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/7.2.0/include/node/v8.h:374: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/7.2.0/include/node/v8.h:442: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/7.2.0/include/node/v8.h:787: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/7.2.0/include/node/v8.h:812: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/7.2.0/include/node/v8.h:824: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: At global scope:
/root/.node-gyp/7.2.0/include/node/v8.h:849: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/7.2.0/include/node/v8.h:1086: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h:1092: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/root/.node-gyp/7.2.0/include/node/v8.h:1621: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/7.2.0/include/node/v8.h:3295: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: At global scope:
/root/.node-gyp/7.2.0/include/node/v8.h:4526: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h:4551: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In constructor ‘v8::Isolate::CreateParams::CreateParams()’:
/root/.node-gyp/7.2.0/include/node/v8.h:5596: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: At global scope:
/root/.node-gyp/7.2.0/include/node/v8.h:6787: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h:6804: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h:6896: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h:6897: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h:7233: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/7.2.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/7.2.0/include/node/v8.h:7804: 错误：‘nullptr’在此作用域中尚未声明
In file included from ../../nan/nan.h:190,
                 from ../lib/utils.h:6,
                 from ../lib/nodejieba.h:4,
                 from ../lib/index.cpp:1:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: 错误：expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: 错误：expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:31: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:36: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:41: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:46: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:51: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:59: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:64: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:69: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:76: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:83: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:91: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:98: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:108: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:114: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:118: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:125: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:130: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:135: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:139: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:145: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:150: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:156: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:162: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:168: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:174: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:180: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:186: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:194: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:201: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:205: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:209: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:213: 错误：expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:217: 错误：expected initializer before ‘<’ token
../lib/index.cpp:24: 错误：expected ‘}’ at end of input
../../nan/nan_callbacks_12_inl.h:167: 警告：‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:181: 警告：‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:197: 警告：‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:253: 警告：‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:270: 警告：‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:290: 警告：‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:306: 警告：‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:323: 警告：‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:428: 警告：‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:444: 警告：‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:464: 警告：‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:480: 警告：‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’定义后未使用
../../nan/nan_callbacks_12_inl.h:496: 警告：‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’定义后未使用
make: *** [Release/obj.target/nodejieba/lib/index.o] 错误 1
make: Leaving directory `/root/node/node_modules/nodejieba/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v7.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v7.2.0/bin/node" "/root/.nvm/versions/node/v7.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node/node_modules/nodejieba
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-project-seed@1.0.0 /root/node
└── pinyin@2.8.0

npm WARN node-project-seed@1.0.0 No description
npm WARN node-project-seed@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nodejieba@2.2.4 (node_modules/nodejieba):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nodejieba@2.2.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by yanyiwu** [comment]
@lilijialiang 这个也 close 掉吧。
