### ISSUE TITLE
ie11出现语法错误问题

### ISSUE THREAD

**Issue by smh1996** [hotoo/pinyin#267]
[vue-router] Failed to resolve async component default: SyntaxError: 语法错误
[vue-router] uncaught error during route navigation:
SyntaxError: 语法错误
   {
      [functions]: ,
      __proto__: { },
      description: "语法错误",
      message: "语法错误",
      name: "SyntaxError",
      number: -2146827286,
      stack: "SyntaxError: 语法错误
   at ./node_modules/pinyin/lib/pinyin.js (http://192.168.54.220:8080/14.41376f354e7d4d14906b.js:45:1)
   at __webpack_require__ (http://192.168.54.220:8080/app.41376f354e7d4d14906b.js:767:12)
   at fn (http://192.168.54.220:8080/app.41376f354e7d4d14906b.js:130:13)
   at eval code (eval code:26:1)
   at ./node_modules/pinyin/lib/web-pinyin.js (http://192.168.54.220:8080/14.41376f354e7d4d14906b.js:57:1)
   at __webpack_require__ (http://192.168.54.220:8080/app.41376f354e7d4d14906b.js:767:12)
   at fn (http://192.168.54.220:8080/app.41376f354e7d4d14906b.js:130:13)
   at eval code (eval code:6:22)
   at ./src/minix/pinyin.js (http://192.168.54.220:8080/28.41376f354e7d4d14906b.js:11:1)
   at __webpack_require__ (http://192.168.54.220:8080/app.41376f354e7d4d14906b.js:767:12)",
      Symbol()_b.pd6uy212iqx: undefined,
      Symbol()_i.pd6uy212ixf: undefined,
      Symbol()_k.pd6uy212ixf: undefined,
      Symbol()_l.pd6uy212ixf: undefined,
      Symbol()_m.pd6uy212ixf: undefined,
      Symbol(react.element)_j.pd6uy212ixf: undefined
   }

SCRIPT7002: XMLHttpRequest: 网络错误 0x2efd, 由于出现错误 00002efd 而导致此项操作无法完成。
class_detail
SCRIPT7002: XMLHttpRequest: 网络错误 0x2efd, 由于出现错误 00002efd 而导致此项操作无法完成。
class_detail
SCRIPT7002: XMLHttpRequest: 网络错误 0x2efd, 由于出现错误 00002efd 而导致此项操作无法完成。
class_detail
SCRIPT7002: XMLHttpRequest: 网络错误 0x2efd, 由于出现错误 00002efd 而导致此项操作无法完成。
class_detail

**Comment by smallsunnyfox** [comment]
@hotoo 在ie11下遇到了类似的问题

**Comment by lu-chao** [comment]
在 ie10 和 ie11 中 都遇到了类似的问题

**Comment by northernCold** [comment]
报错原因是：使用了ie不支持的es6语法
解决方便是：一般自身项目都有配置babel，编译的时候默认是跳过`node_modules`内的文件，只需修改babel的配置，编译`node_modules`内的pinyin

项目中如果使用的是
- vue-cli
vue-cli有便捷的方法
```javascript
// vue.config.js
module.exports = {
  transpileDependencies: [
    'pinyin'
  ]
}
```

- webpack
要修改babel-loader配置include的
```javascript
//webpack.config.js
{
    test: /\.m?jsx?$/,
    include: [
        path.resolve(__dirname, 'src'),
        /pinyin/,
    ],
    use: [
    {
      loader: 'babel-loader'
    }
  ]
}
```

**Comment by hotoo** [comment]
请使用 3.x `npm i pinyin@alpha`
