### ISSUE TITLE
npm install pinyin出问题

### ISSUE THREAD

**Issue by rccoder** [hotoo/pinyin#44]
```
npm WARN engine nodejieba@1.0.3: wanted: {"node":"0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
-
> nodejieba@1.0.3 install /home/rccoder/code/HIT-International/node_modules/pinyin/node_modules/nodejieba
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.19.0-18-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rccoder/code/HIT-International/node_modules/pinyin/node_modules/nodejieba
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.19.0-18-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pinyin"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! nodejieba@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejieba@1.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nodejieba package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodejieba
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rccoder/code/HIT-International/npm-debug.log

```

**Comment by hotoo** [comment]
请提供你的安装命令，及操作系统信息。

**Comment by hotoo** [comment]
请 @yanyiwu 也帮忙看看。

**Comment by rccoder** [comment]
安装命令：```npm install pinyin```
操作系统： Ubuntu Kylin 15.04
node 版本：0.12.0
npm 版本： 2.5.1

**Comment by rccoder** [comment]
是我安装nodejieba的时候就会出现这个问题

**Comment by yanyiwu** [comment]
@rccoder 

请问node-gyp的版本是多少？
```
node-gyp -v
```

**Comment by rccoder** [comment]
@yanyiwu 是```v2.0.1```

**Comment by yanyiwu** [comment]
@rccoder 后来忙，把这个issue给忘了。sorry。不知道你问题解决了没有？
目测是你的node-gyp的版本太新了，有些接口和老版本不兼容。
我看了一下现在node.js 最新源码，使用的仍然还是 1.0.3的版本：https://github.com/joyent/node/blob/master/deps/npm/node_modules/node-gyp/package.json

所以建议你还是使用较低版本的node-gyp吧。

**Comment by yanyiwu** [comment]
我现在使用的版本是 node@0.12.1 , node-gyp@v0.9.6 ,供你参考一下。

**Comment by hotoo** [comment]
iojs 的是 2.0.1

https://github.com/nodejs/io.js/blob/master/deps/npm/node_modules/node-gyp/package.json

**Comment by hotoo** [comment]
感觉是 node-gyp 和 node/npm 不匹配，是不是 nvm/n 什么的 node 版本管理有问题？

**Comment by yanyiwu** [comment]
恩，建议还是使用和node版本配套的node-gyp吧。
也可能是和楼主自己的机器环境有关。
我刚自己安装了一下 node-gyp@v2.0.1 ，然后去 node-gyp rebuild 什么的都没有问题。

**Comment by rccoder** [comment]
@yanyiwu  @hotoo  我是用n管理Node, 全部卸载之后重装了一下，现在没有问题了，谢谢两位~
